branches:
  only: pelican
language: python
python: '2.7'
sudo: false
env:
  global:
  - secure: X7OBUY4L3XJgKbd2k6uK+HiXQC6gGzH5PT0kngShWQRiv4KCPqLGEZyqPcZ0khO1ltSke80J/987ma2humECP0mEkDRJhh4nze0YJZAcXKM3Cd72P1mQZrd2J0DQVpDtPfhJn6SyK/pwmZqI7pa/1UinzHhEEhfuLlnsEHewo8sU9buCvAe6qIymsdYdgU1bH0hT66dAc4WbT0rCFeQk+/MFUXrO9T/MXp5JfSM3UNPzNMbraWBQE/ZxrEUlipiKuPgytyxPGyz8XuipQOuUhdnUtTJAUwtJ4zumBKOhftO0i0HIxNrDtR/8S7uSb1h5+7ckZHlbZv1xYvbduvaM/wpTX6bNgrEtk+KVWBEFYxGR2X9mLnljfUDG1fnaaESvDwnzuRYMDW/iRBb+9e0DQ2EkEFAen6qOd/HykDR/hpNPnA60HFwd/KgNR4pSd0fiUyfp04Jkqzm63B34Wn1GLCJSUq7mrjSOyahub85mzWT82xepfmuFsyodyv0AjZfcRFRJkRKtJGyI7AGHpx7m6QiWluyrNNffgjEe0mxfWZYf3SACBzxsiVKwIP/O2jd6SJ21zxE44V0bE0Wq5qvd0pnWXsTUeo8U0URK2TGVe9+MZ5rXdjX6pR1GUfMoPmNyiI2B1Pd3re0ArPJ79XCW18Ey6LphpfplZVy2Ddxj85Q=
  - secure: XPxDnc8oljNIf9xyiqH0Pg4DYQOfS2Wx5PlcxMX4htVQAp5mHolFSghO5NInw07a3ecIVcDOjdNZG1GieNpOxz7dSD0cDyY8LMtXTlb4YzWw565goI8jATFJhNXYplMUCJgZjJjzTC8Ey/UFpY2RJWVIApLs5dfrDz6iH/4P5R/wnjb2fEcq8yqm1IGDxqwJssrPv5qmPC7hwK04inUXYmUAYSLI3diMBIfYGc+CnXFRuSK4D8SQw0dG5xEb7ZLtfLLX641K2UcY6lK0OFIFyp0fb6dEX5um22F8cVC7GccB2N7pkS5MmKHBC3R8I66reYY5OSspHx6Z9KNUzOkwRE+4xNhNQkvwr1nQG5JA9guL4k4lqcwuTU73vYVnJ9MDrMMbjOY2rNNnyU7nSwhYs3PQ2hJvwXcuX3ImaMFQA6W5J2rMKyDBDO6F8yuDm8OyhFtK0kmRYHXE1uAAzV6j1pFn7HofLhMd9Tjm7vgk1WeVkpJg6pSVuBXzGMicXGPfwBPMcI8WKVS03/07wYaJcn2YKNk2aaaAsR3j6y4uZ9+TU6fkFdqy19+y++1c6lXQTfrzJBcBXXARA7Z+jus+kSp5AhEOtQMjgVrT6oioSudNl54imIl22rLkaK0m8b0xGRZTrscGVWKlq5zFJ04+lJycFTq3AWnGmsGngWjZc4g=
cache: pip
before_script: gem install sass
script: pelican -s publishconf.py
after_success: "./generate.sh deploy"
