branches:
  only: pelican
language: python
python: '2.7'
sudo: false
cache: pip
before_script: gem install sass
script: pelican -s publishconf.py
after_success: "./generate.sh deploy"
env:
  global:
  - secure: PyFeMEowzFbn8+LOS6qSgEtLcRRN3UsVaknhno/EHvVIov50F3hImXvD0ngrFi29eRo466jgy7hGUPop9NQDhbMUvI2nT90UAeNY+8IwDrXs3LK7QZd8nzH/1VlsdIIzcwbOBwx7rugQ5mxSB+Ybojw5bxgu9+c8ksd08adX1+c0vbCsHmeqKZOz/f4xfTnJty2HZmplMHcxOgZRWlRb5cvKgvHiFBm5NkF1UBs0F0ps3LGYUp69u4vEN0QzgBDwqL4cG3ZNEASCXw0AbGsy2ORJ6jLeowx0lkWVG6BBM5iPPEvNPk4CXSf84r8U9FzGHxnyfOTeCUueGRLMKGUUQrVwX6JpUbD21Hg3gP9mx6eYy0p5SA5xyrOqOdEILTyPuubK09OUFkPpA2KOGgFUmKwCkjPm84sy1l56SKlikEWZidkYKkACzrNiUHgXLr3mlyHDnJn+kulUE9n21m1l2wsRnifkbFFIvGKcnqY5oVbNwB6t8IEXVx3I1szwJ06nhgQsNtwvQL+tRd2zzv4SjebvnJhrfy/KH43VA+dMsAxRaEOWlWYBH4N8hBb+uU6/SWeHwUgq+bHhGX094UyXRrhB/qYC6nCAfiLRqvaFBDLYdJI2rEjSh2AF0S4eO7GViY6qJ7RukdgLMJxdK5DgLAmpGaZY60bwgq0lkvcLp1M=
