branches:
  only: pelican
language: python
python: '2.7'
sudo: false
cache: pip
before_script: gem install sass
script: pelican -s publishconf.py
after_success: "./generate.sh deploy"
env:
  global:
    secure: VSPfVBh+UVVrzWUAqFMnu39gndydWR+j+uyQGgB2sISDlp+/7OkxiKFvkYw6mExzJvzt/LCRucj2BjnT8rkJTInonZPLHnz40tCK4iJDVsmllakvTRocPAkPwqnN7PqDkdeYxcw1NJjDmAph2X8aHOvDGw6sVKNrLPfcp40xCkLebir4cUdGFveDViLybawKuA9hWlgTwip7qf43hXpkeecv5ilBMzgUnVIRfKC4wTt2HhjMsKGEc9j5eG2mwqcmcF01C8pevuYWqt7ofNgaIS60n/YIk7kOcnJN1gbZJ+ufEvelmDwzmnNPPWZlbE07S/gKyplQXgehubWqWNB6n9hwWKk1UcSUh1gEtGaVHK+FJwDFgdkvHBHc31aftg2DjieUV28Wh/JlSvi3aBAPp1IkXeblomeLHdYuaRKHdBKFLp4wD62g/CpAio8S5xdT0xtospbh8Pi4MAUYoXUhRrp9zpQq67PP1/mNFBgwP5hfcoyukso1tNbKrVYY86OMrMq11XJQL/SwlprVClk3GLuU8BTK3upuie3v2roNgGfKfozY91OuGWTv7rX7dACYWc0uTf8tybjY5Jgp882+VFGIRPV9DGbMexeDR2ZbtH/+CBkuChrFVp7eIAc9r3qmL+4KVrWSxqKidUIQ7gyoMn186dSlp1sVT7L7uGpw+jA=
