branches:
  only: pelican
language: python
python: '2.7'
sudo: false
cache: pip
before_script: gem install sass
script: pelican -s publishconf.py
after_success: "./generate.sh deploy"
env:
  global:
    secure: d7fisdjeonsj/AxjLb7SJnnljSY5UxKqKmyMgcmTEjFpBIfqOuaODYpdvqF7KQFCqyU8fCQg5sXvlt5Obl6tR/LtvcU8tsmavi//9Oaq1YjfxmVRXr8zADF3FslWVP62LUHxqQ/BgEHL4dSndigEi2JtjI1H20gTe5Fbm4wrwYyC+iZMBlw2Oz5FnWnmElBp4ghkzSf8ZXYQICpe8zW1pb4Ih5HvpaKp0G80AjJmhYJn3GFWu+5lkDkWx15RMsobSgicTi6Yx8yZNhfcOFm0dN8S9+dVL4neAo+pMpNMkMgFKwDoJGNtdLmYQlyzuAhV4WVtpnBHeair5nK6lbEDWHysP7wPvdYLR55nkZ55hiFSbWCJuQdd9BFa2lbRG4AoQkJkwGy2LVzZpPlHzWzBjzRkzrRFOfoxIzjYaxQo5AnzcGg6WLZQt7cZKolcS7zmMMZfyMW7VUBelrVbZV5gutg8Y03kJQkzSr445/YBtxXamyLa0VABNZTWuRWHJ7XI5HypLIyrttrWUAhLoGuCyG+lyrN3laR8D0+Fz/njcxPIwniKBetTuoKHOsC1eTb81fJb1mB1niC/pwRqVKkmuuRnTFWak5TJ9pqALLikIN05UlAHxG8rjvoZx6e+UG6LOrwnY2Gew2rvrV2+2Ab2DkKZ/HfPDCeU0PGaLjVSi2I=
